// Generated by CoffeeScript 1.3.3

define(["./contentView", "form/validationMixin", "form/textField"], function(ContentView, Validation) {
  return ContentView.extend(Validation, {
    template: Ember.Handlebars.compile("<h1>Edit Profile</h1>\n<form class=\"form-horizontal\" id=\"userForm\">\n  {{view TextField valueBinding=\"view.user.email\" viewName=\"email\" label=\"Email\"}}\n  <button class=\"btn btn-primary\" {{action \"save\" target=\"view\"}} type=\"submit\">Save</button>\n </form>\n<fieldset>\n  <legend>Change Password</legend>\n  <form class=\"form-horizontal\" id=\"passwordForm\">\n    {{view TextField viewName=\"password-old\" type=\"password\" label=\"Old Password\"}}\n    {{view TextField viewName=\"password1\" type=\"password\" label=\"New Password\"}}\n    {{view TextField viewName=\"password2\" type=\"password\" label=\"New Password (repeat)\"}}\n    <button class=\"btn btn-primary\" {{action \"changePassword\" target=\"view\"}} type=\"submit\">Change Password</button>\n   </form>\n</fieldset>"),
    navId: "editProfile",
    user: {},
    init: function() {
      var _this = this;
      this._super();
      return $.get("/ajax/user/" + Chat.ticket.username, function(result) {
        return _this.set("user", result);
      });
    },
    save: function() {
      var _this = this;
      return $.post("/ajax/user/", {
        user: this.user,
        "session-id": Chat.ticket["session-id"]
      }, function(result) {
        return _this.handleResponse(result);
      });
    },
    changePassword: function() {
      var _this = this;
      return $.post("/ajax/user/" + Chat.ticket.username + "/password", {
        user: this.user,
        "session-id": Chat.ticket["session-id"]
      }, function(result) {
        return _this.handleResponse(result);
      });
    },
    didInsertElement: function() {
      return this._super();
    }
  });
});
