// Generated by CoffeeScript 1.3.3

define(function() {
  Em.TextField.reopen({
    attributeBindings: ['placeholder', 'disabled', 'maxlength', "name", "type"]
  });
  return window.TextField = Ember.View.extend({
    classNames: ['control-group'],
    classNameBindings: ['status'],
    type: "text",
    template: Ember.Handlebars.compile("<label class=\"control-label\" for=\"{{unbound view.textfield.id}}\">{{view.label}}</label>\n  <div class=\"controls\">\n    {{view Em.TextField valueBinding=\"view.value\" placeholderBinding=\"view.placeholder\"\n    viewName=\"textfield\" nameBinding=\"view.viewName\"\n    disabledBinding=\"view.disabled\" typeBinding=\"view.type\"}}\n    <span class=\"help-inline\">{{view.message}}</span>\n  </div>")
  });
});
